export { composeLayout, compareLayoutGraphs } from './composer';
export type {
  LayoutGraph,
  LayoutNode,
  LayoutEdge,
  LayoutNodeType,
  ComposerInput,
  ComposerResult,
  GridSpec,
  SpacingSpec,
  CompositionProfile,
  FocalPoint,
  GridSystem,
  SpacingRhythmSpec,
  VisualHierarchy,
  GlobalCompositionProfile,
  FlowProfile,
  HeroVariant,
  SplitVariant,
  ClusterVariant,
  StripVariant,
  GalleryVariant,
  SignalVariant,
  EdgeType,
  Depth,
  Density,
  VisualWeight,
  Rhythm,
  BalanceType,
  TensionLevel,
  MediaPlacement,
  CtaPlacement,
  SpacingRhythm,
  LayoutPrimitive,
} from './types';
