import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        playfair: ["var(--font-playfair)", "serif"],
        syne: ["var(--font-syne)", "sans-serif"],
        bricolage: ["var(--font-bricolage)", "sans-serif"],
        cormorant: ["var(--font-cormorant)", "serif"],
        "dm-serif": ["var(--font-dm-serif)", "serif"],
        satoshi: ["var(--font-satoshi)", "sans-serif"],
        hanken: ["Hanken Grotesk", "sans-serif"],
        "headline-lg-mobile": ["Hanken Grotesk"],
        "body-md": ["Hanken Grotesk"],
        "headline-md": ["Hanken Grotesk"],
        "body-lg": ["Hanken Grotesk"],
        "headline-lg": ["Hanken Grotesk"],
        "label-sm": ["Hanken Grotesk"],
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        // Design tokens used by the marketing home page (mirror inline tailwind config)
        "text-secondary": "#65676B",
        "on-secondary": "#ffffff",
        "tertiary-container": "#018800",
        "inverse-primary": "#adc6ff",
        "on-primary": "#ffffff",
        "status-error": "#FA3E3E",
        "on-primary-fixed": "#001a41",
        "on-error": "#ffffff",
        "surface-card": "#FFFFFF",
        "tertiary-fixed-dim": "#5ae148",
        "on-primary-fixed-variant": "#004493",
        "text-primary": "#050505",
        "primary-fixed": "#d8e2ff",
        "on-tertiary-fixed-variant": "#015300",
        "on-surface": "#191c1e",
        "surface-tint": "#005bc0",
        "surface-container-lowest": "#ffffff",
        "on-background": "#191c1e",
        "on-tertiary-fixed": "#002200",
        surface: "#f7f9fc",
        "status-warning": "#F7B928",
        "outline-variant": "#c1c6d6",
        error: "#ba1a1a",
        "border-subtle": "#CED0D4",
        "secondary-container": "#d8e4f0",
        tertiary: "#016c00",
        "surface-variant": "#e0e3e6",
        "secondary-fixed": "#d8e4f0",
        "on-secondary-fixed": "#111d25",
        "on-primary-container": "#fefcff",
        "primary-container": "#0070eb",
        "surface-bright": "#f7f9fc",
        "surface-container": "#eceef1",
        "surface-dim": "#d8dadd",
        "on-secondary-container": "#5a6670",
        outline: "#727785",
        "on-tertiary": "#ffffff",
        "surface-container-highest": "#e0e3e6",
        "secondary-fixed-dim": "#bcc8d3",
        "inverse-on-surface": "#eff1f4",
        "error-container": "#ffdad6",
        "inverse-surface": "#2d3133",
        "surface-container-low": "#f2f4f7",
        "tertiary-fixed": "#78ff62",
        "primary-fixed-dim": "#adc6ff",
        "on-surface-variant": "#414754",
        "on-secondary-fixed-variant": "#3d4852",
        "on-tertiary-container": "#f8ffef",
        "on-error-container": "#93000a",
        "surface-container-high": "#e6e8eb",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "margin-mobile": "16px",
        "margin-desktop": "40px",
        gutter: "24px",
        unit: "4px",
        "container-max": "1280px",
      },
      maxWidth: {
        "container-max": "1280px",
      },
      padding: {
        "margin-mobile": "16px",
        "margin-desktop": "40px",
      },
      fontSize: {
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "600" }],
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "gradient-x": {
          "0%, 100%": { "background-position": "0% 50%" },
          "50%": { "background-position": "100% 50%" },
        },
        "float": {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-10px)" },
        },
        "pulse-glow": {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.5" },
        },
        shimmer: {
          "100%": { transform: "translateX(100%)" },
        },
        typing: {
          from: { width: "0" },
          to: { width: "100%" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "gradient-x": "gradient-x 3s ease infinite",
        float: "float 3s ease-in-out infinite",
        "pulse-glow": "pulse-glow 2s ease-in-out infinite",
        shimmer: "shimmer 2s infinite",
        typing: "typing 2s steps(40, end)",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};

export default config;
