"use client";

import { useState, useEffect } from "react";
import { useSession } from "next-auth/react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { motion, AnimatePresence } from "framer-motion";
import { ArrowRight, Sparkles, Zap, Globe, Shield, Star, ChevronDown, Check, X } from "lucide-react";

const EXAMPLE_PROMPTS = [
  "Shoe store called Ethica with a dark elegant design",
  "Filipino restaurant with warm earthy tones",
  "Photography portfolio with minimalist black and white",
  "Barbershop called Kings Cut with a masculine feel",
  "Online store selling handmade jewelry",
  "Modern dental clinic website",
  "Personal trainer landing page",
  "Coffee shop called Brew & Co",
];

const EXAMPLE_WEBSITES = [
  { name: "Ethica", type: "Shoe Store", gradient: "from-zinc-900 to-stone-800", accent: "#c9a84c" },
  { name: "Brew & Co", type: "Coffee Shop", gradient: "from-amber-900 to-stone-800", accent: "#f59e0b" },
  { name: "KingsCut", type: "Barbershop", gradient: "from-slate-900 to-blue-950", accent: "#3b82f6" },
  { name: "Lumen", type: "Photography", gradient: "from-gray-900 to-zinc-900", accent: "#e5e7eb" },
  { name: "Selah", type: "Wellness Studio", gradient: "from-emerald-950 to-teal-900", accent: "#34d399" },
  { name: "Solana", type: "Jewelry Store", gradient: "from-violet-950 to-purple-900", accent: "#a78bfa" },
];

const FEATURES = [
  {
    icon: Zap,
    title: "Generate in seconds",
    description: "Type your idea, click generate. Get a complete, beautiful website instantly — no design skills needed.",
  },
  {
    icon: Globe,
    title: "Built for the Philippines",
    description: "GCash payments, ₱ pricing, Filipino fonts and aesthetics. Everything your local business needs.",
  },
  {
    icon: Sparkles,
    title: "AI that designs, not templates",
    description: "Every website is uniquely generated by Claude AI. No cookie-cutter templates. Real creative output.",
  },
  {
    icon: Shield,
    title: "Edit everything visually",
    description: "Drag, drop, click to edit. Change text, images, colors — all without touching a single line of code.",
  },
];

const FAQS = [
  {
    q: "Do I need to know how to code?",
    a: "Not at all. Just type what you want and the AI builds it for you. Then click to edit any part of it.",
  },
  {
    q: "How many websites can I create?",
    a: "Free users get 2 AI generations per day. Pro users get unlimited generations.",
  },
  {
    q: "Can I use my own domain?",
    a: "Yes! Pro users can connect any custom domain (e.g. yourbusiness.com). Free users get a free subdomain on storebuilder.ph.",
  },
  {
    q: "What payment methods are supported for online stores?",
    a: "Generated stores support GCash, Maya, GoTyme, credit/debit cards, and BancNet — all Philippine payment methods.",
  },
  {
    q: "Is my website mobile-friendly?",
    a: "Every generated website is fully responsive and looks great on mobile, tablet, and desktop.",
  },
  {
    q: "Can I edit my website after generating?",
    a: "Yes! Editing is completely free and unlimited. Use our drag-and-drop editor to make any changes you want.",
  },
];

export default function HomePage() {
  const { data: session } = useSession();
  const router = useRouter();
  const [prompt, setPrompt] = useState("");
  const [isGenerating, setIsGenerating] = useState(false);
  const [openFaq, setOpenFaq] = useState<number | null>(null);
  const [currentPromptIndex, setCurrentPromptIndex] = useState(0);
  const [displayedPrompt, setDisplayedPrompt] = useState("");
  const [isTyping, setIsTyping] = useState(true);

  // Typewriter animation for example prompts
  useEffect(() => {
    if (prompt) return; // Don't animate if user is typing
    const currentExample = EXAMPLE_PROMPTS[currentPromptIndex];
    let charIndex = 0;
    setIsTyping(true);

    const typeInterval = setInterval(() => {
      if (charIndex <= currentExample.length) {
        setDisplayedPrompt(currentExample.slice(0, charIndex));
        charIndex++;
      } else {
        clearInterval(typeInterval);
        setIsTyping(false);
        setTimeout(() => {
          setCurrentPromptIndex((i) => (i + 1) % EXAMPLE_PROMPTS.length);
        }, 2000);
      }
    }, 40);

    return () => clearInterval(typeInterval);
  }, [currentPromptIndex, prompt]);

  async function handleGenerate() {
    const finalPrompt = prompt || displayedPrompt;
    if (!finalPrompt.trim()) return;

    if (!session) {
      router.push(`/auth/signin?callbackUrl=/dashboard`);
      return;
    }

    setIsGenerating(true);
    router.push(`/dashboard?generate=${encodeURIComponent(finalPrompt)}`);
  }

  return (
    <div className="min-h-screen bg-black text-white">
      {/* Navbar */}
      <nav className="fixed top-0 left-0 right-0 z-50 flex items-center justify-between px-6 py-4 backdrop-blur-md bg-black/50 border-b border-white/5">
        <div className="flex items-center gap-2">
          <div className="w-8 h-8 bg-violet-600 rounded-lg flex items-center justify-center">
            <Sparkles size={16} className="text-white" />
          </div>
          <span className="font-bold text-lg tracking-tight" style={{ fontFamily: "var(--font-syne)" }}>
            Storebuilder.ph
          </span>
        </div>
        <div className="hidden md:flex items-center gap-8 text-sm text-white/60">
          <a href="#features" className="hover:text-white transition-colors">Features</a>
          <a href="#pricing" className="hover:text-white transition-colors">Pricing</a>
          <a href="#faq" className="hover:text-white transition-colors">FAQ</a>
        </div>
        <div className="flex items-center gap-3">
          {session ? (
            <Link href="/dashboard" className="px-4 py-2 bg-violet-600 hover:bg-violet-500 rounded-lg text-sm font-medium transition-colors">
              Dashboard
            </Link>
          ) : (
            <>
              <Link href="/auth/signin" className="text-sm text-white/70 hover:text-white transition-colors">
                Sign in
              </Link>
              <Link href="/auth/register" className="px-4 py-2 bg-violet-600 hover:bg-violet-500 rounded-lg text-sm font-medium transition-colors">
                Get started free
              </Link>
            </>
          )}
        </div>
      </nav>

      {/* Hero Section */}
      <section className="relative min-h-screen flex flex-col items-center justify-center px-4 pt-20 overflow-hidden">
        {/* Background gradient orbs */}
        <div className="absolute inset-0 overflow-hidden pointer-events-none">
          <div className="absolute top-1/4 left-1/4 w-96 h-96 bg-violet-900/30 rounded-full blur-3xl" />
          <div className="absolute bottom-1/4 right-1/4 w-80 h-80 bg-indigo-900/20 rounded-full blur-3xl" />
          <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[600px] h-[600px] bg-purple-950/10 rounded-full blur-3xl" />
        </div>

        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6 }}
          className="text-center max-w-5xl mx-auto relative z-10"
        >
          <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-violet-950/60 border border-violet-500/20 text-violet-300 text-sm mb-8">
            <span className="text-lg">🇵🇭</span>
            <span>The first AI website builder made for the Philippines</span>
          </div>

          <h1 className="text-5xl md:text-7xl lg:text-8xl font-bold mb-6 leading-none tracking-tight" style={{ fontFamily: "var(--font-bricolage)" }}>
            Build your website{" "}
            <span className="bg-gradient-to-r from-violet-400 via-purple-400 to-indigo-400 bg-clip-text text-transparent">
              in seconds
            </span>{" "}
            with AI
          </h1>

          <p className="text-xl md:text-2xl text-white/50 mb-12 max-w-2xl mx-auto leading-relaxed">
            Type what you need. Get a complete, beautiful, fully editable website — instantly.
          </p>

          {/* Prompt Input */}
          <div className="relative max-w-2xl mx-auto">
            <div className="prompt-glow rounded-2xl bg-white/5 border border-white/10 p-2 flex gap-2">
              <input
                type="text"
                value={prompt}
                onChange={(e) => setPrompt(e.target.value)}
                onKeyDown={(e) => e.key === "Enter" && handleGenerate()}
                placeholder={isTyping ? displayedPrompt + "|" : displayedPrompt}
                className="flex-1 bg-transparent px-4 py-3 text-white placeholder-white/30 outline-none text-lg"
              />
              <button
                onClick={handleGenerate}
                disabled={isGenerating}
                className="px-6 py-3 bg-violet-600 hover:bg-violet-500 disabled:opacity-50 rounded-xl font-medium flex items-center gap-2 transition-colors whitespace-nowrap"
              >
                {isGenerating ? (
                  <span className="w-5 h-5 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                ) : (
                  <>
                    <Sparkles size={18} />
                    Generate
                  </>
                )}
              </button>
            </div>

            {/* Example chips */}
            <div className="flex flex-wrap gap-2 mt-4 justify-center">
              {["Shoe store", "Food business", "Photography portfolio", "Barbershop", "Online store", "Salon"].map((chip) => (
                <button
                  key={chip}
                  onClick={() => setPrompt(chip)}
                  className="px-3 py-1.5 rounded-full bg-white/5 hover:bg-white/10 border border-white/10 text-sm text-white/60 hover:text-white/90 transition-colors"
                >
                  {chip}
                </button>
              ))}
            </div>
          </div>

          <p className="mt-6 text-white/30 text-sm">
            Free to start · No credit card required · 2 generations per day free
          </p>
        </motion.div>

        {/* Scroll indicator */}
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 1 }}
          className="absolute bottom-8 left-1/2 -translate-x-1/2"
        >
          <ChevronDown className="text-white/30 animate-bounce" size={24} />
        </motion.div>
      </section>

      {/* Example websites showcase */}
      <section className="py-20 px-4 overflow-hidden">
        <div className="max-w-7xl mx-auto">
          <h2 className="text-center text-3xl md:text-4xl font-bold mb-4" style={{ fontFamily: "var(--font-bricolage)" }}>
            See what gets generated
          </h2>
          <p className="text-center text-white/50 mb-12">Real AI-generated websites, not templates</p>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {EXAMPLE_WEBSITES.map((site, i) => (
              <motion.div
                key={site.name}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: i * 0.1 }}
                className="website-card rounded-2xl overflow-hidden border border-white/10 cursor-pointer group"
              >
                <div className={`bg-gradient-to-br ${site.gradient} h-48 p-6 flex flex-col justify-between relative overflow-hidden`}>
                  <div className="absolute inset-0 opacity-10" style={{ backgroundImage: `radial-gradient(circle at 70% 50%, ${site.accent}, transparent)` }} />
                  <div className="relative">
                    <div className="text-xs font-medium px-2 py-1 rounded-full inline-block" style={{ background: `${site.accent}20`, color: site.accent, border: `1px solid ${site.accent}30` }}>
                      {site.type}
                    </div>
                  </div>
                  <div className="relative">
                    <h3 className="text-2xl font-bold" style={{ fontFamily: "var(--font-playfair)", color: site.accent }}>
                      {site.name}
                    </h3>
                    <div className="mt-2 flex gap-1">
                      {[...Array(3)].map((_, j) => (
                        <div key={j} className="h-1 rounded-full flex-1 opacity-30" style={{ background: site.accent }} />
                      ))}
                    </div>
                  </div>
                </div>
                <div className="bg-zinc-900 p-4 flex items-center justify-between">
                  <span className="text-sm text-white/50">AI Generated</span>
                  <span className="text-xs text-white/30 flex items-center gap-1">
                    <Sparkles size={12} />
                    Unique design
                  </span>
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section id="features" className="py-20 px-4 bg-zinc-950">
        <div className="max-w-6xl mx-auto">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="text-center mb-16"
          >
            <h2 className="text-3xl md:text-5xl font-bold mb-4" style={{ fontFamily: "var(--font-bricolage)" }}>
              Everything you need to{" "}
              <span className="bg-gradient-to-r from-violet-400 to-indigo-400 bg-clip-text text-transparent">
                go online
              </span>
            </h2>
            <p className="text-white/50 text-lg max-w-2xl mx-auto">
              From AI generation to publishing — all in one place, built specifically for Filipino businesses.
            </p>
          </motion.div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {FEATURES.map((f, i) => (
              <motion.div
                key={f.title}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: i * 0.1 }}
                className="p-6 rounded-2xl bg-white/3 border border-white/8 hover:border-violet-500/30 transition-colors"
              >
                <div className="w-12 h-12 rounded-xl bg-violet-950 border border-violet-800/50 flex items-center justify-center mb-4">
                  <f.icon size={22} className="text-violet-400" />
                </div>
                <h3 className="text-lg font-bold mb-2">{f.title}</h3>
                <p className="text-white/50 leading-relaxed">{f.description}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* How it works */}
      <section className="py-20 px-4">
        <div className="max-w-4xl mx-auto">
          <h2 className="text-center text-3xl md:text-5xl font-bold mb-16" style={{ fontFamily: "var(--font-bricolage)" }}>
            Three steps to your website
          </h2>
          <div className="space-y-8">
            {[
              { step: "01", title: "Describe your website", desc: "Tell the AI what kind of website you need. Be as specific or vague as you like — it understands." },
              { step: "02", title: "AI generates it instantly", desc: "Claude AI creates a complete, unique website with custom sections, colors, content, and layout in seconds." },
              { step: "03", title: "Edit, publish, and grow", desc: "Click anything to edit it. Publish your site instantly to a free subdomain or your own custom domain." },
            ].map((item, i) => (
              <motion.div
                key={item.step}
                initial={{ opacity: 0, x: -20 }}
                whileInView={{ opacity: 1, x: 0 }}
                viewport={{ once: true }}
                transition={{ delay: i * 0.15 }}
                className="flex gap-6 items-start"
              >
                <div className="text-5xl font-bold text-violet-900/50" style={{ fontFamily: "var(--font-playfair)" }}>
                  {item.step}
                </div>
                <div className="pt-2">
                  <h3 className="text-xl font-bold mb-2">{item.title}</h3>
                  <p className="text-white/50 leading-relaxed">{item.desc}</p>
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Pricing Section */}
      <section id="pricing" className="py-20 px-4 bg-zinc-950">
        <div className="max-w-4xl mx-auto">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="text-center mb-16"
          >
            <h2 className="text-3xl md:text-5xl font-bold mb-4" style={{ fontFamily: "var(--font-bricolage)" }}>
              Simple, honest pricing
            </h2>
            <p className="text-white/50 text-lg">Start free. Upgrade when you're ready.</p>
          </motion.div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {/* Free Plan */}
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              className="p-8 rounded-2xl border border-white/10 bg-white/2"
            >
              <div className="mb-6">
                <h3 className="text-xl font-bold mb-1">Free</h3>
                <div className="text-4xl font-bold">₱0 <span className="text-lg font-normal text-white/40">/ forever</span></div>
              </div>
              <ul className="space-y-3 mb-8">
                {[
                  "2 AI website generations per day",
                  "Unlimited editing",
                  "Free subdomain (yourname.storebuilder.ph)",
                  "All editor features",
                  "Powered by Claude Haiku",
                ].map((item) => (
                  <li key={item} className="flex items-start gap-3 text-white/70">
                    <Check size={18} className="text-violet-400 mt-0.5 shrink-0" />
                    {item}
                  </li>
                ))}
                {["Custom domain", "Remove branding"].map((item) => (
                  <li key={item} className="flex items-start gap-3 text-white/30">
                    <X size={18} className="mt-0.5 shrink-0" />
                    {item}
                  </li>
                ))}
              </ul>
              <Link href="/auth/register" className="w-full block text-center py-3 px-6 rounded-xl border border-white/20 hover:border-white/40 transition-colors font-medium">
                Get started free
              </Link>
            </motion.div>

            {/* Pro Plan */}
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ delay: 0.1 }}
              className="p-8 rounded-2xl border border-violet-500/50 bg-gradient-to-b from-violet-950/50 to-transparent relative overflow-hidden"
            >
              <div className="absolute top-4 right-4 px-3 py-1 bg-violet-600 rounded-full text-xs font-bold">
                POPULAR
              </div>
              <div className="mb-6">
                <h3 className="text-xl font-bold mb-1">Pro</h3>
                <div className="text-4xl font-bold">₱299 <span className="text-lg font-normal text-white/40">/ month</span></div>
                <div className="text-sm text-white/40 mt-1">or ₱2,499/year (save ₱1,089)</div>
              </div>
              <ul className="space-y-3 mb-8">
                {[
                  "Unlimited AI website generations",
                  "Unlimited editing",
                  "Custom domain connection",
                  "All editor features",
                  "Powered by Claude Sonnet (smarter)",
                  "Priority support",
                  "Remove Storebuilder.ph branding",
                  "Advanced section library",
                ].map((item) => (
                  <li key={item} className="flex items-start gap-3 text-white/70">
                    <Check size={18} className="text-violet-400 mt-0.5 shrink-0" />
                    {item}
                  </li>
                ))}
              </ul>
              <Link href="/auth/register?upgrade=pro" className="w-full block text-center py-3 px-6 rounded-xl bg-violet-600 hover:bg-violet-500 transition-colors font-medium">
                Start Pro free trial
              </Link>
            </motion.div>
          </div>
        </div>
      </section>

      {/* Social Proof */}
      <section className="py-16 px-4">
        <div className="max-w-4xl mx-auto text-center">
          <div className="flex justify-center gap-1 mb-4">
            {[...Array(5)].map((_, i) => <Star key={i} size={20} className="text-amber-400 fill-amber-400" />)}
          </div>
          <p className="text-xl text-white/70 italic mb-4 max-w-2xl mx-auto">
            "I had my barbershop website live in under 3 minutes. My clients can now book online directly. Sobrang ganda ng result!"
          </p>
          <p className="text-white/40 text-sm">— Carlo M., Kings Cut Barbershop, Quezon City</p>
        </div>
      </section>

      {/* FAQ Section */}
      <section id="faq" className="py-20 px-4 bg-zinc-950">
        <div className="max-w-2xl mx-auto">
          <h2 className="text-3xl font-bold text-center mb-12" style={{ fontFamily: "var(--font-bricolage)" }}>
            Frequently asked questions
          </h2>
          <div className="space-y-2">
            {FAQS.map((faq, i) => (
              <div key={i} className="rounded-xl border border-white/8 overflow-hidden">
                <button
                  onClick={() => setOpenFaq(openFaq === i ? null : i)}
                  className="w-full text-left px-6 py-4 flex items-center justify-between hover:bg-white/3 transition-colors"
                >
                  <span className="font-medium">{faq.q}</span>
                  <ChevronDown
                    size={18}
                    className={`text-white/40 transition-transform ${openFaq === i ? "rotate-180" : ""}`}
                  />
                </button>
                <AnimatePresence>
                  {openFaq === i && (
                    <motion.div
                      initial={{ height: 0 }}
                      animate={{ height: "auto" }}
                      exit={{ height: 0 }}
                      className="overflow-hidden"
                    >
                      <div className="px-6 pb-4 text-white/50 leading-relaxed">
                        {faq.a}
                      </div>
                    </motion.div>
                  )}
                </AnimatePresence>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Final CTA */}
      <section className="py-24 px-4 text-center">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
        >
          <h2 className="text-4xl md:text-6xl font-bold mb-6" style={{ fontFamily: "var(--font-bricolage)" }}>
            Your website is{" "}
            <span className="bg-gradient-to-r from-violet-400 to-indigo-400 bg-clip-text text-transparent">
              30 seconds away
            </span>
          </h2>
          <p className="text-white/50 text-lg mb-8">Free forever. No credit card. No code.</p>
          <Link href="/auth/register" className="inline-flex items-center gap-2 px-8 py-4 bg-violet-600 hover:bg-violet-500 rounded-xl font-medium text-lg transition-colors">
            Build my website now
            <ArrowRight size={20} />
          </Link>
        </motion.div>
      </section>

      {/* Footer */}
      <footer className="border-t border-white/8 py-12 px-4">
        <div className="max-w-6xl mx-auto flex flex-col md:flex-row items-center justify-between gap-6">
          <div className="flex items-center gap-2">
            <div className="w-6 h-6 bg-violet-600 rounded-md flex items-center justify-center">
              <Sparkles size={12} className="text-white" />
            </div>
            <span className="font-bold" style={{ fontFamily: "var(--font-syne)" }}>Storebuilder.ph</span>
          </div>
          <div className="flex gap-6 text-sm text-white/40">
            <a href="#" className="hover:text-white transition-colors">Privacy</a>
            <a href="#" className="hover:text-white transition-colors">Terms</a>
            <a href="mailto:hello@storebuilder.ph" className="hover:text-white transition-colors">Contact</a>
          </div>
          <p className="text-sm text-white/30">© 2025 Storebuilder.ph 🇵🇭</p>
        </div>
      </footer>
    </div>
  );
}
